export interface KenyanCounty {
  name: string;
  slug: string;
  region: string;
  majorTown: string;
  keywords: string[];
  description: string;
  constituencies: string[];
}

export const kenyanCounties: KenyanCounty[] = [
  {
    name: 'Mombasa',
    slug: 'mombasa',
    region: 'Coast',
    majorTown: 'Mombasa',
    keywords: ['Mombasa web development', 'Mombasa ERP systems', 'Mombasa software company', 'Coast Kenya IT services'],
    description: 'Leading software and IT solutions in Mombasa, Kenya\'s premier port city and commercial hub.',
    constituencies: ['Changamwe', 'Jomvu', 'Kisauni', 'Nyali', 'Likoni', 'Mvita'],
  },
  {
    name: 'Nairobi',
    slug: 'nairobi',
    region: 'Central',
    majorTown: 'Nairobi',
    keywords: ['Nairobi web development', 'Nairobi ERP systems', 'Nairobi software company', 'Kenya tech hub IT services'],
    description: 'Top-rated software company in Nairobi, Kenya\'s capital and East Africa\'s tech innovation hub.',
    constituencies: ['Starehe', 'Kamukunji', 'Dagoretti North', 'Dagoretti South', 'Kasarani', 'Roysambu', 'Kenyatta', 'Makadara', 'Langata', 'Westlands', 'Diani', 'Kileleshwa', 'Loresho', 'Karanga', 'Mwiki', 'Githurai', 'Ruai'],
  },
  {
    name: 'Kisumu',
    slug: 'kisumu',
    region: 'Western',
    majorTown: 'Kisumu',
    keywords: ['Kisumu web development', 'Kisumu ERP systems', 'Kisumu software company', 'Lake Region IT services'],
    description: 'Professional IT solutions in Kisumu, Kenya\'s western gateway and lakeside city.',
    constituencies: ['Kisumu West', 'Kisumu East', 'Kisumu Central', 'Seme', 'Nyando', 'Muhoroni', 'Nyakach'],
  },
  {
    name: 'Nakuru',
    slug: 'nakuru',
    region: 'Rift Valley',
    majorTown: 'Nakuru',
    keywords: ['Nakuru web development', 'Nakuru ERP systems', 'Nakuru software company', 'Rift Valley IT services'],
    description: 'Reliable software and web development services in Nakuru, Rift Valley\'s economic center.',
    constituencies: ['Naivasha', 'Gilgil', 'Kuresoi South', 'Kuresoi North', 'Molo', 'Njoro', 'Rongai', 'Bahati', 'Subukia', 'Nakuru Town West', 'Nakuru Town East'],
  },
  {
    name: 'Eldoret',
    slug: 'eldoret',
    region: 'Rift Valley',
    majorTown: 'Eldoret',
    keywords: ['Eldoret web development', 'Eldoret ERP systems', 'Eldoret software company', 'Uasin Gishu IT services'],
    description: 'Sports city IT solutions - web development and software services in Eldoret, Kenya.',
    constituencies: ['Soy', 'Turbo', 'Ainabkoi', 'Kapseret', 'Kesses', 'Moiben'],
  },
  {
    name: 'Machakos',
    slug: 'machakos',
    region: 'Eastern',
    majorTown: 'Machakos',
    keywords: ['Machakos web development', 'Machakos ERP systems', 'Machakos software company', 'Eastern Kenya IT services'],
    description: 'Eastern Kenya software solutions in Machakos, a growing industrial hub.',
    constituencies: ['Masinga', 'Yatta', 'Kangundo', 'Matungulu', 'Kathiani', 'Mavoko', 'Machakos Town', 'Mwala'],
  },
  {
    name: 'Meru',
    slug: 'meru',
    region: 'Eastern',
    majorTown: 'Meru',
    keywords: ['Meru web development', 'Meru ERP systems', 'Meru software company', 'Mount Kenya IT services'],
    description: 'Mount Kenya region software and IT services in Meru.',
    constituencies: ['Igembe South', 'Igembe Central', 'Igembe North', 'Tigania West', 'Tigania East', 'North Imenti', 'Buuri', 'Central Imenti', 'South Imenti'],
  },
  {
    name: 'Kitui',
    slug: 'kitui',
    region: 'Eastern',
    majorTown: 'Kitui',
    keywords: ['Kitui web development', 'Kitui ERP systems', 'Kitui software company'],
    description: 'Eastern Kenya IT solutions and web development services in Kitui.',
    constituencies: ['Mwingi North', 'Mwingi West', 'Mwingi Central', 'Kitui West', 'Kitui Rural', 'Kitui Central', 'Kitui East', 'Kitui South'],
  },
  {
    name: 'Garissa',
    slug: 'garissa',
    region: 'North Eastern',
    majorTown: 'Garissa',
    keywords: ['Garissa web development', 'Garissa ERP systems', 'Garissa software company', 'North Eastern IT services'],
    description: 'North Eastern Kenya software solutions and IT services.',
    constituencies: ['Garissa Township', 'Balambala', 'Lagdera', 'Dadaab', 'Fafi', 'Ijara'],
  },
  {
    name: 'Malindi',
    slug: 'malindi',
    region: 'Coast',
    majorTown: 'Malindi',
    keywords: ['Malindi web development', 'Malindi ERP systems', 'Malindi software company', 'Coast Kenya IT services'],
    description: 'Coastal Kenya web development and software services in Malindi.',
    constituencies: ['Kilifi North', 'Kilifi South', 'Kaloleni', 'Rabai', 'Ganze', 'Malindi', 'Magarini'],
  },
  {
    name: 'Kakamega',
    slug: 'kakamega',
    region: 'Western',
    majorTown: 'Kakamega',
    keywords: ['Kakamega web development', 'Kakamega ERP systems', 'Kakamega software company', 'Western Kenya IT services'],
    description: 'Western Kenya software solutions in Kakamega, the province\'s capital.',
    constituencies: ['Lurambi', 'Navakholo', 'Malava', 'Lugari', 'Likuyani', 'Mumias West', 'Mumias East', 'Matungu', 'Butere', 'Khwisero', 'Shinyalu', 'Ikolomani'],
  },
  {
    name: 'Kericho',
    slug: 'kericho',
    region: 'Rift Valley',
    majorTown: 'Kericho',
    keywords: ['Kericho web development', 'Kericho ERP systems', 'Kericho software company', 'Tea belt IT services'],
    description: 'Rift Valley software services in Kericho, Kenya\'s tea growing capital.',
    constituencies: ['Bomet', 'Chepalungu', 'Sigowet-Soin', 'Kipkelion', 'Londiani', 'Ketu South', 'Ketu North', 'Bureti', 'Tinderet'],
  },
  {
    name: 'Thika',
    slug: 'thika',
    region: 'Central',
    majorTown: 'Thika',
    keywords: ['Thika web development', 'Thika ERP systems', 'Thika software company', 'Central Kenya IT services'],
    description: 'Central Kenya industrial town software and IT solutions in Thika.',
    constituencies: ['Gatundu South', 'Gatundu North', 'Juja', 'Thika Town', 'Ruiru', 'Githunguri', 'Kiambu', 'Kiambaa', 'Kabete', 'Kikuyu', 'Limuru', 'Lari'],
  },
  {
    name: 'Nyeri',
    slug: 'nyeri',
    region: 'Central',
    majorTown: 'Nyeri',
    keywords: ['Nyeri web development', 'Nyeri ERP systems', 'Nyeri software company', 'Central Kenya IT services'],
    description: 'Central Kenya software solutions in Nyeri, near Mount Kenya.',
    constituencies: ['Tetu', 'Kieni', 'Mathira', 'Othaya', 'Mukurweini', 'Nyeri Town'],
  },
  {
    name: 'Kisii',
    slug: 'kisii',
    region: 'Western',
    majorTown: 'Kisii',
    keywords: ['Kisii web development', 'Kisii ERP systems', 'Kisii software company', 'Nyanza IT services'],
    description: 'Western Kenya software and web development in Kisii.',
    constituencies: ['Kitutu Chache North', 'Kitutu Chache South', 'Nyaribari Masaba', 'Nyaribari Chache', 'Bonchari', 'South Mugirango', 'Bobasi', 'Bomachoge Borabu', 'Bomachoge Chache'],
  },
  {
    name: 'Migori',
    slug: 'migori',
    region: 'Western',
    majorTown: 'Migori',
    keywords: ['Migori web development', 'Migori ERP systems', 'Migori software company'],
    description: 'Nyanza region software solutions in Migori.',
    constituencies: ['Awendo', 'Kuria East', 'Kuria West', 'Nyatike', 'Rongo', 'Sun'],
  },
  {
    name: 'Bungoma',
    slug: 'bungoma',
    region: 'Western',
    majorTown: 'Bungoma',
    keywords: ['Bungoma web development', 'Bungoma ERP systems', 'Bungoma software company', 'Western Kenya IT services'],
    description: 'Western Kenya border town software solutions in Bungoma.',
    constituencies: ['Bungoma North', 'Kimilili', 'Mt. Elgon', 'Sirisia', 'Kabuchai', 'Kanduyi', 'Webuye East', 'Webuye West'],
  },
  {
    name: 'Busia',
    slug: 'busia',
    region: 'Western',
    majorTown: 'Busia',
    keywords: ['Busia web development', 'Busia ERP systems', 'Busia software company', 'Border town IT services'],
    description: 'Kenya-Uganda border software and IT services in Busia.',
    constituencies: ['Teso North', 'Teso South', 'Nambale', 'Matayos', 'Butula', 'Funyula', 'Bunyala'],
  },
  {
    name: 'Kajiado',
    slug: 'kajiado',
    region: 'Rift Valley',
    majorTown: 'Kajiado',
    keywords: ['Kajiado web development', 'Kajiado ERP systems', 'Kajiado software company', 'Greater Nairobi IT services'],
    description: 'Greater Nairobi region software services in Kajiado.',
    constituencies: ['Kajiado North', 'Kajiado Central', 'Kajiado East', 'Kajiado West', 'Kajiado South'],
  },
  {
    name: 'Kiambu',
    slug: 'kiambu',
    region: 'Central',
    majorTown: 'Kiambu',
    keywords: ['Kiambu web development', 'Kiambu ERP systems', 'Kiambu software company', 'Greater Nairobi IT services'],
    description: 'Greater Nairobi satellite town software solutions.',
    constituencies: ['Gatundu South', 'Gatundu North', 'Juja', 'Thika Town', 'Ruiru', 'Githunguri', 'Kiambu', 'Kiambaa', 'Kabete', 'Kikuyu', 'Limuru', 'Lari'],
  },
  {
    name: 'Laikipia',
    slug: 'laikipia',
    region: 'Rift Valley',
    majorTown: 'Nanyuki',
    keywords: ['Laikipia web development', 'Laikipia ERP systems', 'Laikipia software company'],
    description: 'Rift Valley software services in Laikipia County.',
    constituencies: ['Laikipia West', 'Laikipia North', 'Laikipia East'],
  },
  {
    name: 'Isiolo',
    slug: 'isiolo',
    region: 'Eastern',
    majorTown: 'Isiolo',
    keywords: ['Isiolo web development', 'Isiolo ERP systems', 'Isiolo software company', 'Northern Kenya IT services'],
    description: 'Northern Kenya gateway software solutions in Isiolo.',
    constituencies: ['Isiolo North', 'Isiolo South'],
  },
  {
    name: 'Marsabit',
    slug: 'marsabit',
    region: 'Eastern',
    majorTown: 'Marsabit',
    keywords: ['Marsabit web development', 'Marsabit ERP systems', 'Marsabit software company'],
    description: 'Northern Kenya software and IT services in Marsabit.',
    constituencies: ['Moyale', 'North Horr', 'Saku', 'Laisamis'],
  },
  {
    name: 'Turkana',
    slug: 'turkana',
    region: 'Western',
    majorTown: 'Lodwar',
    keywords: ['Turkana web development', 'Turkana ERP systems', 'Turkana software company', 'North Western Kenya IT services'],
    description: 'North Western Kenya software solutions in Turkana.',
    constituencies: ['Turkana North', 'Turkana West', 'Turkana Central', 'Turkana East', 'Turkana South', 'Loima'],
  },
  {
    name: 'Samburu',
    slug: 'samburu',
    region: 'Rift Valley',
    majorTown: 'Maralal',
    keywords: ['Samburu web development', 'Samburu ERP systems', 'Samburu software company'],
    description: 'Central Rift Valley software services in Samburu.',
    constituencies: ['Samburu West', 'Samburu North', 'Samburu East'],
  },
  {
    name: 'Nyandarua',
    slug: 'nyandarua',
    region: 'Central',
    majorTown: 'Ol Kalou',
    keywords: ['Nyandarua web development', 'Nyandarua ERP systems', 'Nyandarua software company'],
    description: 'Central Kenya software solutions in Nyandarua.',
    constituencies: ['Kinangop', 'Kipipiri', 'Ol Kalou', 'Ol Jorok', 'Ndaragwa'],
  },
  {
    name: 'Kirinyaga',
    slug: 'kirinyaga',
    region: 'Central',
    majorTown: 'Kutus',
    keywords: ['Kirinyaga web development', 'Kirinyaga ERP systems', 'Kirinyaga software company'],
    description: 'Mount Kenya region software services in Kirinyaga.',
    constituencies: ['Mwea', 'Gichuga', 'Ndia', 'Kirinyaga Central'],
  },
  {
    name: 'Muranga',
    slug: 'muranga',
    region: 'Central',
    majorTown: 'Muranga',
    keywords: ['Muranga web development', 'Muranga ERP systems', 'Muranga software company'],
    description: 'Central Kenya software and IT solutions in Muranga.',
    constituencies: ['Kangema', 'Mathioya', 'Kiharu', 'Kigumo', 'Maragwa', 'Kandara', 'Gatanga'],
  },
  {
    name: 'Embu',
    slug: 'embu',
    region: 'Eastern',
    majorTown: 'Embu',
    keywords: ['Embu web development', 'Embu ERP systems', 'Embu software company', 'Eastern Kenya IT services'],
    description: 'Eastern Kenya software solutions in Embu.',
    constituencies: ['Manyatta', 'Runyenjes', 'Mbeere South', 'Mbeere North'],
  },
  {
    name: 'Makueni',
    slug: 'makueni',
    region: 'Eastern',
    majorTown: 'Wote',
    keywords: ['Makueni web development', 'Makueni ERP systems', 'Makueni software company'],
    description: 'Eastern Kenya semi-arid region software services.',
    constituencies: ['Mbooni', 'Kilome', 'Kaiti', 'Makueni', 'Kibwezi West', 'Kibwezi East'],
  },
  {
    name: 'Taita Taveta',
    slug: 'taita-taveta',
    region: 'Coast',
    majorTown: 'Wundanyi',
    keywords: ['Taita Taveta web development', 'Taita Taveta ERP systems', 'Taita Taveta software company'],
    description: 'Coastal highlands software solutions.',
    constituencies: ['Taveta', 'Wundanyi', 'Mwatate', 'Voi'],
  },
  {
    name: 'Kilifi',
    slug: 'kilifi',
    region: 'Coast',
    majorTown: 'Kilifi',
    keywords: ['Kilifi web development', 'Kilifi ERP systems', 'Kilifi software company', 'Coast Kenya IT services'],
    description: 'Coastal Kenya software and IT services in Kilifi.',
    constituencies: ['Kilifi North', 'Kilifi South', 'Kaloleni', 'Rabai', 'Ganze', 'Malindi', 'Magarini'],
  },
  {
    name: 'Kwale',
    slug: 'kwale',
    region: 'Coast',
    majorTown: 'Kwale',
    keywords: ['Kwale web development', 'Kwale ERP systems', 'Kwale software company'],
    description: 'South Coast Kenya software solutions.',
    constituencies: ['Msambweni', 'Lungalunga', 'Matuga', 'Kinango'],
  },
  {
    name: 'Lamu',
    slug: 'lamu',
    region: 'Coast',
    majorTown: 'Lamu',
    keywords: ['Lamu web development', 'Lamu ERP systems', 'Lamu software company', 'Island IT services'],
    description: 'Lamu Island software and IT solutions.',
    constituencies: ['Lamu East', 'Lamu West'],
  },
  {
    name: 'Tana River',
    slug: 'tana-river',
    region: 'Coast',
    majorTown: 'Hola',
    keywords: ['Tana River web development', 'Tana River ERP systems', 'Tana River software company'],
    description: 'Coastal river basin software services.',
    constituencies: ['Garsen', 'Galole', 'Bura'],
  },
  {
    name: 'Mandera',
    slug: 'mandera',
    region: 'North Eastern',
    majorTown: 'Mandera',
    keywords: ['Mandera web development', 'Mandera ERP systems', 'Mandera software company', 'Border IT services'],
    description: 'Kenya-Ethiopia-Somalia border software solutions.',
    constituencies: ['Mandera West', 'Banissa', 'Mandera North', 'Mandera South', 'Mandera East', 'Lafey'],
  },
  {
    name: 'Wajir',
    slug: 'wajir',
    region: 'North Eastern',
    majorTown: 'Wajir',
    keywords: ['Wajir web development', 'Wajir ERP systems', 'Wajir software company', 'North Eastern IT services'],
    description: 'North Eastern Kenya regional services.',
    constituencies: ['Wajir North', 'Wajir East', 'Tarbaj', 'Wajir West', 'Eldas', 'Wajir South'],
  },
  {
    name: 'West Pokot',
    slug: 'west-pokot',
    region: 'Rift Valley',
    majorTown: 'Kapenguria',
    keywords: ['West Pokot web development', 'West Pokot ERP systems', 'West Pokot software company'],
    description: 'Western Rift Valley software services.',
    constituencies: ['Kapenguria', 'Sigor', 'Kacheliba', 'Pokot South'],
  },
  {
    name: 'Trans Nzoia',
    slug: 'trans-nzoia',
    region: 'Rift Valley',
    majorTown: 'Kitale',
    keywords: ['Trans Nzoia web development', 'Trans Nzoia ERP systems', 'Trans Nzoia software company', 'Wheat belt IT services'],
    description: 'Kenya\'s breadbasket software solutions.',
    constituencies: ['Kwanza', 'Endebes', 'Saboti', 'Kiminini', 'Cherangany'],
  },
  {
    name: 'Uasin Gishu',
    slug: 'uasin-gishu',
    region: 'Rift Valley',
    majorTown: 'Eldoret',
    keywords: ['Uasin Gishu web development', 'Uasin Gishu ERP systems', 'Uasin Gishu software company'],
    description: 'Rift Valley software hub in Uasin Gishu.',
    constituencies: ['Soy', 'Turbo', 'Ainabkoi', 'Kapseret', 'Kesses', 'Moiben'],
  },
  {
    name: 'Elgeyo Marakwet',
    slug: 'elgeyo-marakwet',
    region: 'Rift Valley',
    majorTown: 'Iten',
    keywords: ['Elgeyo Marakwet web development', 'Elgeyo Marakwet ERP systems', 'Elgeyo Marakwet software company'],
    description: 'Rungwe sports and IT services.',
    constituencies: ['Marakwet East', 'Marakwet West', 'Keiyo North', 'Keiyo South'],
  },
  {
    name: 'Nandi',
    slug: 'nandi',
    region: 'Rift Valley',
    majorTown: 'Kapsabet',
    keywords: ['Nandi web development', 'Nandi ERP systems', 'Nandi software company'],
    description: 'Rift Valley tea region software services.',
    constituencies: ['Tinderet', 'Aldai', 'Nandi Hills', 'Chesumei', 'Emgwen', 'Mosop'],
  },
  {
    name: 'Baringo',
    slug: 'baringo',
    region: 'Rift Valley',
    majorTown: 'Kabarnet',
    keywords: ['Baringo web development', 'Baringo ERP systems', 'Baringo software company'],
    description: 'Rift Valley lakes region software.',
    constituencies: ['Tiaty', 'Baringo North', 'Baringo Central', 'Mogotio', 'Baringo South'],
  },
  {
    name: 'Narok',
    slug: 'narok',
    region: 'Rift Valley',
    majorTown: 'Narok',
    keywords: ['Narok web development', 'Narok ERP systems', 'Narok software company', 'Maasai Mara IT services'],
    description: 'Rift Valley tourism hub software services.',
    constituencies: ['Narok North', 'Narok East', 'Narok South', 'Narok West', 'Transmara West', 'Transmara East'],
  },
  {
    name: 'Bomet',
    slug: 'bomet',
    region: 'Rift Valley',
    majorTown: 'Bomet',
    keywords: ['Bomet web development', 'Bomet ERP systems', 'Bomet software company'],
    description: 'Rift Valley software solutions.',
    constituencies: ['Bomet Central', 'Bomet East', 'Bomet West', 'Chepalungu', 'Konoin'],
  },
  {
    name: 'Vihiga',
    slug: 'vihiga',
    region: 'Western',
    majorTown: 'Mbale',
    keywords: ['Vihiga web development', 'Vihiga ERP systems', 'Vihiga software company'],
    description: 'Western Kenya software services.',
    constituencies: ['Vihiga', 'Sabatia', 'Hamisi', 'Luanda', 'Emuhaya'],
  },
  {
    name: 'Siaya',
    slug: 'siaya',
    region: 'Western',
    majorTown: 'Siaya',
    keywords: ['Siaya web development', 'Siaya ERP systems', 'Siaya software company', 'Lake Region IT services'],
    description: 'Lake region software solutions.',
    constituencies: ['Ugenya', 'Ugunja', 'Alego Usonga', 'Gem', 'Bondo', 'Rarieda'],
  },
  {
    name: 'Homa Bay',
    slug: 'homa-bay',
    region: 'Western',
    majorTown: 'Homa Bay',
    keywords: ['Homa Bay web development', 'Homa Bay ERP systems', 'Homa Bay software company', 'Lake Region IT services'],
    description: 'Lake Victoria software services.',
    constituencies: ['Ndhiwa', 'Kabondo Kasipul', 'Kasipul', 'Karachuonyo', 'Homa Bay Town', 'Rangwe', 'Suba North', 'Suba South'],
  },
  {
    name: 'Nyamira',
    slug: 'nyamira',
    region: 'Western',
    majorTown: 'Nyamira',
    keywords: ['Nyamira web development', 'Nyamira ERP systems', 'Nyamira software company'],
    description: 'Western Kenya highlands software.',
    constituencies: ['Nyamira', 'Borabu', 'Masaba', 'Manga', 'West Mugirango'],
  },
];

export const getCountyBySlug = (slug: string) => kenyanCounties.find(c => c.slug === slug);

export const getAllCountySlugs = () => kenyanCounties.map(c => c.slug);

export const getConstituencyBySlug = (countySlug: string, constituencySlug: string) => {
  const county = getCountyBySlug(countySlug);
  if (!county) return null;
  const cleanedSlug = constituencySlug.replace(/[^a-z0-9-]/g, '');
  return county.constituencies.find(c => c.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') === cleanedSlug);
};

export const getAllLocations = () => {
  const locations: { county: KenyanCounty; constituency?: string }[] = [];
  for (const county of kenyanCounties) {
    locations.push({ county });
    for (const constituency of county.constituencies) {
      locations.push({ county, constituency });
    }
  }
  return locations;
};